### PR TITLE
fix error TS4029.

### PR DESCRIPTION
**Pull request by kir4ik**
error on export - separating code into files for reuse

ProductTable.ts
```ts
import {Table} from 'ts-sql-query/Table';
import {CustomBooleanTypeAdapter} from 'ts-sql-query/TypeAdapter';
import DBConnection from '../DBConnection';

class ProductTable extends Table<DBConnection, 'ProductTable'> {
  id = this.autogeneratedPrimaryKey('id', 'int');

  constructor() {
    super('product');
  }
}

export default ProductTable;
```

### CODE REVIEW

**Comment by juanluispaz** [comment]
Hi,

I'm only able to reproduce this bug when you have in your tsconfig:

```json
{
    "declaration": true
}
```

Are you trying to build a shared library for access to the database?

That definition are private because they are not stable.

I'm going to take your pull request as inspiration and I'm going to move that definitions to another folder that is not compromised to be stable.

**Comment by juanluispaz** [comment]
Understood.

I will release a new version addressing it tonight

**Comment by kir4ik** [comment]
Thank you

**Comment by juanluispaz** [comment]
Release ts-sql-query 1.27.0 with this changes.

Please, let me know if you identify any other issue like this one.

**Pull request merged**
